# Generated by Django 5.2.3 on 2026-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
